### ISSUE TITLE
Decide on what pages we will need

### ISSUE THREAD

**Issue by jared-skinner** [arfink/BISS-TEA#5]
We need to know what pages we will need for this to be a functioning application.  

What pages will an average user be able to access?

Will there be and admin pages?  If so what?

**Comment by arfink** [comment]
So, pages. Here's my suggestions.

Outside landing page: will display overview and login prompt

Inside landing page (AKA home): after login, user will see this page.
- Quick entry fields: user can immediately use these to quickly enter a new order. Fields the user will need to fill out include description, date, price, account/brand, location/route, and salesman. Date should auto-fill to today's date on page-load or refresh, but can be edited. Account/brand will be a drop-down to pre-selected accounts (set by user on profile page) and all other fields will be blank. 
- Summary view: display last (n) number of orders, sorted by date in descending order (newest on top)
- Search/generate report function (unsure how to implement best at this time, likely best to search between dates, by account/brand, or by arbitrary field?)
- Account controls: link to profile page
- Admin control: if user is detected as admin privileged, display link to admin page

Profile Page
- change password
- update email
- controls to update account list pre-sets

Admin Page
- ??? PROFIT (not sure what admin functions will be needed yet)
- Probably admin needs to be able to add/remove users, since this site is not intended for self-signup
- Probably admin needs to be able to globally edit/search/generate report from any user, possibly allow admin to masquerade as other user?
